
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Table table1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textLog;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView connectedUses;

	private global::Gtk.Entry serverIp;

	private global::Gtk.Label serverIpLabel;

	private global::Gtk.Button startServer;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("SharpChat");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(10)), ((uint)(6)), true);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textLog = new global::Gtk.TextView();
		this.textLog.CanFocus = true;
		this.textLog.Name = "textLog";
		this.textLog.Editable = false;
		this.GtkScrolledWindow.Add(this.textLog);
		this.table1.Add(this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(10));
		w2.RightAttach = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.connectedUses = new global::Gtk.TreeView();
		this.connectedUses.CanFocus = true;
		this.connectedUses.Name = "connectedUses";
		this.GtkScrolledWindow1.Add(this.connectedUses);
		this.table1.Add(this.GtkScrolledWindow1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.GtkScrolledWindow1]));
		w4.BottomAttach = ((uint)(10));
		w4.LeftAttach = ((uint)(4));
		w4.RightAttach = ((uint)(6));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.serverIp = new global::Gtk.Entry();
		this.serverIp.CanFocus = true;
		this.serverIp.Name = "serverIp";
		this.serverIp.IsEditable = true;
		this.serverIp.InvisibleChar = '•';
		this.table1.Add(this.serverIp);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.serverIp]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(3));
		// Container child table1.Gtk.Table+TableChild
		this.serverIpLabel = new global::Gtk.Label();
		this.serverIpLabel.Name = "serverIpLabel";
		this.serverIpLabel.Xalign = 1F;
		this.serverIpLabel.LabelProp = global::Mono.Unix.Catalog.GetString("IP-address:");
		this.table1.Add(this.serverIpLabel);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.serverIpLabel]));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.startServer = new global::Gtk.Button();
		this.startServer.CanFocus = true;
		this.startServer.Name = "startServer";
		this.startServer.UseUnderline = true;
		this.startServer.Label = global::Mono.Unix.Catalog.GetString("Start server");
		this.table1.Add(this.startServer);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.startServer]));
		w7.LeftAttach = ((uint)(3));
		w7.RightAttach = ((uint)(4));
		this.Add(this.table1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 673;
		this.DefaultHeight = 379;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.startServer.Clicked += new global::System.EventHandler(this.OnStartServerClicked);
	}
}
